server:
  port: ${PORT:5000}

logging:
  level:
    root: INFO

spring:
  datasource:
    default: ${APP_ENV}
    development:
      url: jdbc:h2:~/kameleoon
      username: sa
      password:
    production:
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      url: ${DATABASE_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

springdoc:
  swagger-ui:
    path: /swagger